[LP 412] add link errors to landing page
plaid/quickstart pull request #208
Opened 2021-04-20 20:30 UTC by lindawoo-plaid

Jira ticket:  https://jira.plaid.com/browse/LP-412

before: 
![image](https://user-images.githubusercontent.com/77688518/115459699-33de0f00-a1dc-11eb-8ff9-dfd65d3aeb36.png)

after: 
![image](https://user-images.githubusercontent.com/77688518/115459633-22950280-a1dc-11eb-98d0-0ccffa8ad6c2.png)

2021-04-20 23:39 UTC, phoenixy1 approved these changes
Approving from a behavior POV; did not review for code quality

2021-04-21 18:41 UTC, skylarmb requested changes

2021-04-21 18:41 UTC, skylarmb commented on frontend/src/Components/Headers/index.tsx
> +          linkToken == null && backend === true ? (
```suggestion
          linkToken == null && backend ? (
```

2021-04-21 18:41 UTC, skylarmb commented on frontend/src/Components/Headers/index.tsx
> +          {backend === false ? (
```suggestion
          {!backend ? (
```

2021-04-21 18:41 UTC, skylarmb commented on frontend/src/App.tsx
> +              linkErrorCode: data.error.error_code,
These variable names are a bit confusing to me as this error is not a Link error (which is something else), it's a Link token API error right?. Maybe we could just add one key to the state that represents the actual error object and do something like this

```suggestion
              linkTokenError: data.error,
```

then later in the template 

```jsx

Error Code: <code>{linkTokenError.error_code}</code>

```

etc

2021-04-23 20:20 UTC, skylarmb approved these changes

2021-04-23 20:21 UTC, merged